### ISSUE TITLE
A dark theme progress bar window for 7-Zip

### ISSUE THREAD

**Issue by jupiter104** [mcmilk/7-Zip#17]
![1363](https://user-images.githubusercontent.com/24752210/181878995-bf97fa24-c358-4fc6-866b-7354692a1e3a.jpg)

Hi guys. This is the best program for zipping/unzipping files. Very fast performance. So, congrats for making this awesome tool.

One thing I've noticed is that people are increasingly preferring dark themes which makes it easier on their eyes. So, I think it would be great if you could make 7-Zip detect whether a dark theme is being used on the Operating System and accordingly make 7-Zip's progress window also dark like the photoshopped image above.

**Comment by mcmilk** [comment]
This is a 7-Zip archive ... nothing more

**Comment by shodanx2** [comment]
mcmilk, it does not cost you anything to let people give feedback here. 
Unless you believe 7-zip is getting too much feedback already and the users need to quiet down ?

**Comment by mcmilk** [comment]
I have no problem with dark theme and so on ... but I will not do it - I have no time for this.
I am not using 7-Zip personally ... I just need a fast compression for some things @ work ... but this was in 2016 ... ;)

**Comment by shodanx2** [comment]
I mean, yours is the first result for "7-zip github issues"
If people have feedback, this is where they'd post it.
Don't take it as taking the responsibility to answer what is written here.
Just let people write 
Maybe let the 7zip dev team about it, maybe the 7zip source forge forum mods could  take care of this ?

If you really want to be hands off about it, simply create a new repo with a new user, something like 7-Zip/7-Zip and let it be.

**Comment by mcmilk** [comment]
I can disable the issues / pull request on `7-Zip` here ... maybe thats better... I will think about this.
